server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: portfolio-backend
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:my-email@gmail.com}
    password: ${MAIL_PASSWORD:my-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

cors:
  allowed-origins: http://localhost:4200,http://localhost:4201
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# File upload configuration
app:
  upload:
    dir: uploads
    max-file-size: 5MB
    max-request-size: 10MB

logging:
  level:
    com.portfolio.backend: DEBUG
    org.springframework.security: DEBUG
